
- name: change users shell to bash
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/local/bin/bash

- name: disable fortune (bash)
  ansible.builtin.lineinfile:
    path: "/home/{{ user }}/.profile"
    line: '#if [ -x /usr/bin/fortune ] ; then /usr/bin/fortune freebsd-tips ; fi'
    regex: '^if [ -x /usr/bin/fortune ]'

- name: set editor (bash)
  ansible.builtin.lineinfile:
    path: "/home/{{ user }}/.profile"
    line: 'EDITOR=ee;      export EDITOR'
    regex: '^EDITOR'
