- name: install node_exporter
  ansible.builtin.command: pkg install -y node_exporter

- name: enable node_exporter
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: node_exporter_enable=YES
    regex: ^node_exporter_enable

- name: start node_exporter
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: true

- name: enable node_exporter traffic in pf
  ansible.builtin.lineinfile:
    path: /etc/pf.conf
    line: 'pass in proto tcp to port { 9100 }'
    insertafter: '# -- incremental pass rules --'

- name: enable node_exporter traffic in pf (comment)
  ansible.builtin.lineinfile:
    path: /etc/pf.conf
    line: '# enable node_exporter'
    insertafter: '# -- incremental pass rules --'

- name: restart pf
  ansible.builtin.service:
    name: pf
    state: restarted
