- name: enable wx (elf32)
  ansible.builtin.lineinfile:
    path: /boot/loader.conf
    line: kern.elf32.allow_wx=0

- name: enable wx (elf64)
  ansible.builtin.lineinfile:
    path: /boot/loader.conf
    line: kern.elf64.allow_wx=0

- name: enable alsr (elf32)
  ansible.builtin.lineinfile:
    path: /boot/loader.conf
    line: kern.elf32.aslr.enable=1

- name: enable alsr (elf64)
  ansible.builtin.lineinfile:
    path: /boot/loader.conf
    line: kern.elf64.aslr.enable=1

- name: enable pie (elf32)
  ansible.builtin.lineinfile:
    path: /boot/loader.conf
    line: kern.elf32.aslr.pie_enable=1

- name: enable pie (elf64)
  ansible.builtin.lineinfile:
    path: /boot/loader.conf
    line: kern.elf32.allow_wx=0