
- name: include rc.conf changes
  ansible.builtin.include_tasks: rcconf.yml

- name: include sysctl changes
  ansible.builtin.include_tasks: sysctl.yml

- name: include cron hardening
  ansible.builtin.include_tasks: cron.yml

- name: include loader hardening
  ansible.builtin.include_tasks: loader.yml

- name: include security level
  ansible.builtin.include_tasks: securelevel.yml

- name: include login hardening
  ansible.builtin.include_tasks: login.yml

- name: include root-only files
  ansible.builtin.include_tasks: rootfiles.yml
