- name: clean tmp on boot
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: clear_tmp_enable="YES"

- name: disable sendmail
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: sendmail_enable=”NONE”

- name: disable inetd
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: inetd_enable=”NO”

- name: disable NFS server
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: nfs_server_enable=”NO”

- name: disable NFS client
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: nfs_client_enable=”NO”

- name: disable portmap
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: portmap_enable=”NO”

- name: disable syslog logging to network
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: syslogd_flags=”-ss”




  