#https://gist.github.com/jahil/4565d8dfa06254f0c11d
- name: set permissions on root to root only
  ansible.builtin.file:
    path: /root
    owner: root
    group: wheel
    mode: '0710'

- name: touch /etc/rc.local
  ansible.builtin.file:
    path: '/etc/rc.local'
    mode: '0710'
    owner: root
    group: wheel
    state: touch

#https://gist.github.com/jahil/4565d8dfa06254f0c11d
- name: set permissions on root-only files
  ansible.builtin.file:
    path: "{{ item }}"
    mode: 'o='
  with_items: "{{ rootfiles }}"
