- name: enable kernel security level
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: kern_securelevel_enable="YES"
    regex: ^kern_securelevel_enable

- name: set kernel security level
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: kern_securelevel="2"
    regex: ^kern_securelevel
