
# https://docs.freebsd.org/en/books/handbook/security/
- name: blackhole tcp
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: net.inet.tcp.blackhole=2

# https://docs.freebsd.org/en/books/handbook/security/  
- name: blackhole udp
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: net.inet.udp.blackhole=1

# https://docs.freebsd.org/en/books/handbook/security/  
- name: disable icmp redirect
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: net.inet.icmp.drop_redirect=1

# https://docs.freebsd.org/en/books/handbook/security/  
- name: disable ip redirect
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: net.inet.ip.redirect=0

# https://docs.freebsd.org/en/books/handbook/security/  
- name: disable source routing (1)
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: net.inet.ip.sourceroute=0

# https://docs.freebsd.org/en/books/handbook/security/  
- name: disable source routing (2)
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: net.inet.ip.accept_sourceroute=0

# https://docs.freebsd.org/en/books/handbook/security/  
- name: don't echo broadcasts
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: net.inet.icmp.bmcastecho=0

# https://docs.freebsd.org/en/books/handbook/security/  
- name: disable users from seeing other's processes
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: security.bsd.see_other_uids=0

# https://docs.freebsd.org/en/books/handbook/security/  
- name: disable users from seeing other group's processes
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: security.bsd.see_other_gids=0