- name: enable pf in rc.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: pf_enable="YES"
    regex: pf_enable

- name: location of pf.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: pf_rules="/etc/pf.conf"
    regex: pf_rules

- name: enable pflog in rc.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: pflog_enable="YES"
    regex: pflog_enable

- name: location of pflog
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: pflog_logfile="/var/log/pflog"
    regex: pflog_logfile

- name: copy pf.conf
  ansible.builtin.copy:
    src: pf.conf
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: '0600'

- name: load pf kernel module
  ansible.builtin.command:
    cmd: "kldload -n pf"

- name: enable pf
  ansible.builtin.command:
    cmd: "pfctl -e"
  ignore_errors: true
  async: 60
  poll: 2

- name: Reset ssh connection
  ansible.builtin.meta: reset_connection

- name: load pf rules
  ansible.builtin.command:
    cmd: "pfctl -f /etc/pf.conf"
  async: 45
  poll: 5

- name: Reset ssh connection
  ansible.builtin.meta: reset_connection

- name: start pflog
  ansible.builtin.service:
    name: pflog
    state: started



