- name: enable pf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: pf_enable="YES"
  become: true
  become_method: su
  become_user: root

- name: enable pflog
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: pflog_enable="YES"
  become: true
  become_method: su
  become_user: root

- name: copy pf.conf
  ansible.builtin.copy:
    src: pf.conf
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: '0644'
  become: true
  become_method: su
  become_user: root

- name: start pf
  ansible.builtin.service:
    name: pf
    state: started
  become: true
  become_method: su
  become_user: root

- name: Wait 600 seconds for target connection to become reachable/usable
  ansible.builtin.wait_for_connection:

- name: start pflog
  ansible.builtin.service:
    name: pflog
    state: started
  become: true
  become_method: su
  become_user: root


