- name: enable pf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: pf_enable="YES"
    regex: ^pf_enable

- name: location of pf.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: pf_rules="/etc/pf.conf"
    regex: ^pf_rules

- name: enable pflog
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: pflog_enable="YES"
    regex: ^pflog_enable

- name: location of pflog
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: pflog_logfile="/var/log/pflog"
    regex: ^pflog_logfile

- name: copy pf.conf
  ansible.builtin.copy:
    src: pf.conf
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: '0600'

#- name: start pf
#  ansible.builtin.service:
#    name: pf
#    state: started

#- name: Wait 600 seconds for target connection to become reachable/usable
#  ansible.builtin.wait_for_connection:

#- name: start pflog
#  ansible.builtin.service:
#    name: pflog
#    state: started



