- name: install java
  ansible.builtin.command: pkg install -y openjdk19

- name: add fdesc fs
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: 'fdesc   /dev/fd         fdescfs         rw      0       0'

- name: add proc fs
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: 'proc    /proc           procfs          rw      0       0'

- name: mount procfs and fdescfs
  ansible.builtin.command: mount -a


